# Generated by Django 2.0 on 2018-07-13 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seg',
            name='seguindo',
        ),
        migrations.AddField(
            model_name='seg',
            name='canal_seguido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to='account.Canal'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='seguidor',
            field=models.ManyToManyField(blank=True, related_name='segue', through='account.Seg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seg',
            name='seguidores',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sendo_seguido_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
