# Generated by Django 2.0 on 2018-06-20 20:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='audio_fundo',
            field=models.FileField(blank=True, null=True, upload_to=account.models.Canal.audio_fundo_path),
        ),
        migrations.AlterField(
            model_name='canal',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.Canal.capa_path),
        ),
    ]
