# Generated by Django 2.0 on 2018-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180712_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='canal',
            name='googleplus',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='canal',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='canal',
            name='twitch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='canal',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='canal',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
