# Generated by Django 2.0 on 2018-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180804_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='numero_seguidores',
            field=models.IntegerField(default=0),
        ),
    ]
