# Generated by Django 2.0 on 2018-09-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_canal_numero_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='comentarista',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='comentario_em_questao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='comentarista',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
