# Generated by Django 2.0 on 2018-09-18 21:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180901_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.PositiveIntegerField()),
                ('audio_name', models.CharField(max_length=50, null=True)),
                ('audio_data', models.DateTimeField(default=datetime.datetime.now)),
                ('audio_canal', models.CharField(max_length=1000, null=True)),
                ('audio_capa', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='canal',
            name='users_notific',
            field=models.ManyToManyField(blank=True, related_name='notifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='canal',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificaudio',
            name='user_notific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notific', to=settings.AUTH_USER_MODEL),
        ),
    ]
