# Generated by Django 2.0 on 2018-09-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180918_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaudio',
            name='user_notific',
        ),
        migrations.DeleteModel(
            name='NotificAudio',
        ),
    ]
