# Generated by Django 2.0 on 2018-06-23 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180622_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='nome_canal',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='O nome do canal deve ser alfanumérico ou conter números.', regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
