# Generated by Django 2.0 on 2018-10-07 16:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181007_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img_perfil',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to=account.models.MyUser.user_directory_path),
        ),
    ]
