# Generated by Django 2.0 on 2018-06-20 01:17

import channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=10)),
                ('visibilidade', models.CharField(max_length=11)),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('audio', models.FileField(blank=True, null=True, upload_to=channel.models.Audio.audio_path)),
                ('capa', models.ImageField(blank=True, null=True, upload_to=channel.models.Audio.capa_path)),
                ('duracao', models.CharField(max_length=15)),
                ('reproducoes', models.IntegerField()),
                ('descricao', models.TextField(max_length=500)),
                ('categoria', models.CharField(max_length=15)),
                ('anuncios', models.ManyToManyField(to='account.Anuncio')),
                ('canal_proprietario', models.ManyToManyField(to='account.Canal')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('Audio_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_do_feed', to='channel.Audio')),
                ('conta_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_do_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('audios', models.ManyToManyField(to='channel.Audio')),
                ('proprietarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='feedback',
            field=models.ManyToManyField(related_name='feedback', through='channel.FeedBack', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audio',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audio',
            name='tag',
            field=models.ManyToManyField(to='channel.Tag'),
        ),
    ]
