# Generated by Django 2.0 on 2018-07-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20180716_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='proprietarios',
            new_name='proprietario',
        ),
        migrations.AddField(
            model_name='playlist',
            name='visibilidade',
            field=models.CharField(choices=[(0, 'publico'), (1, 'privada')], default='publico', max_length=20),
        ),
    ]
