# Generated by Django 2.0 on 2018-07-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20180716_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
