# Generated by Django 2.0 on 2018-07-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180712_2105'),
        ('channel', '0006_playlist_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='descricao',
            field=models.TextField(default=None),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='canal',
        ),
        migrations.AddField(
            model_name='playlist',
            name='canal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='canal_playlist', to='account.Canal'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibilidade',
            field=models.CharField(choices=[('publico', 'público'), ('privada', 'privada')], default='publico', max_length=20),
        ),
    ]
