# Generated by Django 2.0 on 2018-08-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20180723_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='numero_de_audios',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='audio',
            name='anuncios',
            field=models.ManyToManyField(blank=True, null=True, to='account.Anuncio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='categoria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='duracao',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='visibilidade',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
