# Generated by Django 2.0 on 2018-08-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_auto_20180811_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='numero_deslikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audio',
            name='numero_likes',
            field=models.IntegerField(default=0),
        ),
    ]
