# Generated by Django 2.0 on 2018-08-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_auto_20180820_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='reproducoes',
            field=models.IntegerField(default=0),
        ),
    ]
