# Generated by Django 2.0 on 2018-09-01 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0011_playlist_reproducoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('likes', models.IntegerField()),
                ('deslikes', models.IntegerField()),
                ('comentario_em_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Comentario')),
                ('comentarista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='anuncios',
            field=models.ManyToManyField(blank=True, to='account.Anuncio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='audio_comentado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.Audio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentarista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
