# Generated by Django 2.0 on 2018-09-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_auto_20180901_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
