# Generated by Django 2.0 on 2018-09-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_auto_20180901_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='audio_comentado',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.Audio'),
        ),
    ]
