# Generated by Django 2.0 on 2018-09-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0015_auto_20180901_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='deslikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='deslikes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
