# Generated by Django 2.0 on 2018-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0016_auto_20180901_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='possui_resposta',
            field=models.BooleanField(default=False),
        ),
    ]
