# Generated by Django 2.0 on 2018-09-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0017_comentario_possui_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='possui_resposta',
            field=models.IntegerField(default=0),
        ),
    ]
