# Generated by Django 2.0 on 2018-09-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0019_auto_20180902_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='parent',
        ),
    ]
