# Generated by Django 2.0 on 2018-09-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20180901_1609'),
        ('channel', '0020_auto_20180902_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('descricao', models.TextField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_reported', to='channel.Audio')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canal_reported', to='account.Canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
