# Generated by Django 2.0 on 2018-09-21 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0024_auto_20180918_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feeddeslike',
            name='data_do_feed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedlike',
            name='data_do_feed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificaudio',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_notific', to='channel.Audio'),
        ),
        migrations.AddField(
            model_name='notificaudio',
            name='user_notific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notific', to=settings.AUTH_USER_MODEL),
        ),
    ]
