# Generated by Django 2.0 on 2018-09-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0025_auto_20180921_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaudio',
            name='visualized',
            field=models.BooleanField(default=False),
        ),
    ]
