# Generated by Django 2.0 on 2018-09-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0026_notificaudio_visualized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
