# Generated by Django 2.0 on 2018-09-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0027_auto_20180922_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='audio',
            field=models.ManyToManyField(blank=True, null=True, to='channel.Audio'),
        ),
    ]
