# Generated by Django 2.0 on 2018-09-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0028_auto_20180923_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='audio',
            field=models.ManyToManyField(blank=True, to='channel.Audio'),
        ),
    ]
