# Generated by Django 2.0 on 2018-09-24 17:46

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0029_auto_20180923_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(null=True, upload_to=channel.models.Audio.audio_path),
        ),
        migrations.AlterField(
            model_name='audio',
            name='capa',
            field=models.ImageField(null=True, upload_to=channel.models.Audio.capa_path),
        ),
    ]
