# Generated by Django 2.0 on 2018-09-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0031_auto_20180925_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='duracao',
        ),
    ]
