# Generated by Django 2.0 on 2018-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0032_remove_audio_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duracao',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
