# Generated by Django 2.0 on 2018-10-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0035_remove_favorito_data_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='prop',
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
