# Generated by Django 2.0 on 2018-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0036_auto_20181002_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='anuncios',
        ),
        migrations.AddField(
            model_name='audio',
            name='pos_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
