# Generated by Django 2.0 on 2018-10-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0037_auto_20181006_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='pos_rank_av',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
