# Generated by Django 2.0 on 2018-10-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0038_audio_pos_rank_av'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='pos_rank',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='pos_rank_av',
        ),
    ]
