# Generated by Django 2.0 on 2018-10-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0039_auto_20181006_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='aparicoes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
