# Generated by Django 2.0 on 2018-10-11 17:34

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0040_tag_aparicoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='aparicoes',
            field=models.PositiveIntegerField(blank=True, default=channel.models.Tag.get_aparicoes),
        ),
    ]
