# Generated by Django 2.0 on 2018-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0042_remove_tag_aparicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='copia',
            field=models.BooleanField(default=False),
        ),
    ]
