# Generated by Django 2.0 on 2018-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0043_playlist_copia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='copia',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
